[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

# alacritty-themes package from AUR is a good way to view and apply themes
# Also, check out the themes at https://github.com/eendroroy/alacritty-theme
#
# Alacritty themes that I really like:
#   * Alacritty Default
#   * Baskerville - Farside
#   * Greenscreen.dark
#   * Jasonwryan
#   * Jwr-dark
#   * Kasugano
#   * Molokai
#   * OK100 - Matrix
#   * Tokyonight_Night
#   * Visiblue
#   * github_dark_default
